# Form implementation generated from reading ui file 'ui/UI_easyterminal.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets



class Ui_EasyTerminal(object):
    def setupUi(self, EasyTerminal):
        EasyTerminal.setObjectName("EasyTerminal")
        EasyTerminal.resize(440, 294)
        EasyTerminal.setMouseTracking(False)
   
        self.centralwidget = QtWidgets.QWidget(parent=EasyTerminal)
        self.centralwidget.setObjectName("centralwidget")
        self.gr_drivelist = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gr_drivelist.setGeometry(QtCore.QRect(226, 10, 201, 261))

        self.gr_drivelist.setObjectName("gr_drivelist")
        self.btn_tmopen = QtWidgets.QPushButton(parent=self.gr_drivelist)
        self.btn_tmopen.setGeometry(QtCore.QRect(110, 224, 81, 30))
        self.btn_tmopen.setObjectName("btn_tmopen")
        self.list_drive = QtWidgets.QListView(parent=self.gr_drivelist)
        self.list_drive.setGeometry(QtCore.QRect(10, 20, 181, 201))
        self.list_drive.setObjectName("list_drive")

        self.gr_toollist = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gr_toollist.setGeometry(QtCore.QRect(10, 10, 201, 261))
        self.gr_toollist.setObjectName("gr_toollist")

        self.btn_installtm = QtWidgets.QPushButton(parent=self.gr_toollist)
        self.btn_installtm.setGeometry(QtCore.QRect(8, 20, 181, 41))
        self.btn_installtm.setObjectName("btn_installtm")

        self.btn_installgitbash = QtWidgets.QPushButton(parent=self.gr_toollist)
        self.btn_installgitbash.setGeometry(QtCore.QRect(8, 60, 181, 41))
        self.btn_installgitbash.setObjectName("btn_installgitbash")

        self.btn_installpowershell = QtWidgets.QPushButton(parent=self.gr_toollist)
        self.btn_installpowershell.setGeometry(QtCore.QRect(8, 100, 181, 41))
        self.btn_installpowershell.setObjectName("btn_installpowershell")
        
        EasyTerminal.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=EasyTerminal)
        self.statusbar.setObjectName("statusbar")
        EasyTerminal.setStatusBar(self.statusbar)

        self.retranslateUi(EasyTerminal)
        QtCore.QMetaObject.connectSlotsByName(EasyTerminal)

    def retranslateUi(self, EasyTerminal):
        _translate = QtCore.QCoreApplication.translate
        EasyTerminal.setWindowTitle(_translate("EasyTerminal", "EasyTerminal"))
        self.gr_drivelist.setTitle(_translate("EasyTerminal", "Drive Box"))
        self.btn_tmopen.setText(_translate("EasyTerminal", "터미널 열기"))
        self.gr_toollist.setTitle(_translate("EasyTerminal", "Tool Box"))
        self.btn_installtm.setText(_translate("EasyTerminal", "Windows Terminal 설치하기"))
        self.btn_installgitbash.setText(_translate("EasyTerminal", "Git Bash 설치하기"))
        self.btn_installpowershell.setText(_translate("EasyTerminal", "Powershell 설치하기"))
